### ISSUE TITLE
Have junebug create channel logs folder

### ISSUE THREAD

**Issue by rudigiesler** [praekelt/junebug#104]
By default, junebug uses the folder `logs/` to place all the channel log files in. But, if this folder doesn't exist, Junebug throws an error. We should first try to create the folder before throwing an error.

**Comment by hodgestar** [comment]
The place to put this is probably in https://github.com/praekelt/junebug/blob/c324f3b08f4e14f1c2f49705c14a86b64a1d8f35/junebug/logging_service.py#L113 ?

**Comment by rudigiesler** [comment]
Resolved by https://github.com/praekelt/junebug/pull/105
