### ISSUE TITLE
Add support for virtual channels

### ISSUE THREAD

**Issue by hodgestar** [praekelt/junebug#106]
Currently Junebug provides no tools for routing messages from SMPP binds (or other channels). There are currently two important use cases:
- **Number portability** -- the ability to tie together a number of channels that connect to different MNOs into a single channel that forwards messages to and from the appropriate MNO channel (using Portia to decide which MNO to send to).
- **Multiple numbers over a single bind** -- the ability to split one channel that sends and receives messages for multiple numbers (`to_addr`es) into multiple channels that each send and receive messages for a single number.

Virtual channels will be a type of channel that have no associated worker and instead use their configuration to describe message routing.

The message routing would be implemented in the HTTP message receiving and HTTP / AMQP message sending workers. When a message is sent, the virtual channel is was sent from will be recorded so that events may be routed back via the virtual channel status URL if required (we already potentially store a per-message status URL, so this won't require an additional Redis look up).

As for ordinary channels, virtual channel configuration will be stored in Redis. If necessary, virtual channel configuration may be cached locally in memory for a short period of time (e.g. 60 seconds) to handle high-load scenarios.

**Comment by rudigiesler** [comment]
The problem that lead to this issue should mostly be resolved by the implementation of routers:
https://junebug.readthedocs.io/en/latest/routers.html
