### ISSUE TITLE
SMPP Channel delete errors

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/junebug#96]
When deleting an SMPP channel (in this instance it never sucessfully worked, but I don't know if that's relevant) the following error shows:
```json
{
  "status": 500,
  "code": "Internal Server Error",
  "description": "generic error",
  "result": {
    "errors": [
      {
        "message": "'SmppTransceiverTransport' object has no attribute 'service'",
        "type": "AttributeError"
      }
    ]
  }
}
```

**Comment by hodgestar** [comment]
This most likely needs to be fixed in core Vumi, so I've opened https://github.com/praekelt/vumi/issues/1043 and I'm closing this one.
